package com.smartwaste.adminbackend.model;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

// @Document tells Spring this is a MongoDB collection (table)
@Document(collection = "bins")
// @Data from Lombok automatically creates getters, setters, constructors
@Data
public class Bin {

    @Id
    private String id; // Unique ID generated by MongoDB

    private String name; // e.g., "Galle Face Bin 01"
    private Location location; // Nested object for coordinates
    private Double capacity; // e.g., 100.0 (in Liters)
    private Double fillLevel; // e.g., 75.5 (as a percentage)
    private WasteType wasteType; // ORGANIC, NON_ORGANIC, MIXED
    private BinStatus status; // e.g., "EMPTY", "FILLING", "FULL"

    // We need a nested class for the location
    @Data
    public static class Location {
        private double latitude;
        private double longitude;
    }

    // Enum for Waste Type (as you requested)
    public enum WasteType {
        ORGANIC, // Decaying
        NON_ORGANIC, // Non-decaying
        MIXED
    }

    // Enum for Bin Status
    public enum BinStatus {
        EMPTY,
        FILLING,
        FULL,
        OVERFLOWING,
        MAINTENANCE
    }
}